### ISSUE TITLE
Error when trying this...

### ISSUE THREAD

**Issue by rynote** [theta360developers/ThetaS-MultiPictureCapture#1]
```
Traceback (most recent call last):
  File "thetaExample.py", line 218, in <module>
    main()
  File "thetaExample.py", line 199, in main
    fileUrl = takePicture(lastFileUrl)
  File "thetaExample.py", line 125, in takePicture
    id = response["id"]
KeyError: 'id'
```

Getting this when run from pythonista iOS and from macOS 10.13.2

**Comment by BobWhiteWO3B** [comment]
Which theta are you connected to when you run this script?  It was tested against a Theta S.
Bob
